import { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'
import TheHeader from '@/components/TheHeader'
import TheFooter from '@/components/TheFooter'
import { SessionProvider } from "next-auth/react"
import MySessionProvider from '@/providers/MySessionProvider'

const inter = Inter({ subsets: ['latin'] })
 
export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <MySessionProvider>
            <div className="body min-h-screen flex flex-col relative pb-20">
              <TheHeader/>
              <main>
                {children}
              </main>
              <TheFooter/>
            </div>
          </MySessionProvider>
      </body>
    </html>
  )
}
